=== 0000duck/mes/mes-core/src/main/resources/com/qcadoo/mes/core/model.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/model" xmlns="http://www.qcadoo.com/model">

	<xs:element name="models">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="model" type="modelType" />
			</xs:choice>
			<xs:attribute name="plugin" type="identifierType" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="modelType">
		<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="integer" type="fieldType" />
				<xs:element name="string" type="fieldType" />
				<xs:element name="text" type="fieldType" />
				<xs:element name="decimal" type="fieldType" />
				<xs:element name="datetime" type="fieldType" />
				<xs:element name="date" type="fieldType" />
				<xs:element name="boolean" type="fieldType" />
				<xs:element name="belongsTo" type="belongsToFieldType" />
				<xs:element name="hasMany" type="hasManyFieldType" />
				<xs:element name="enum" type="enumFieldType" />
				<xs:element name="dictionary" type="dictionaryFieldType" />
				<xs:element name="password" type="fieldType" />
			</xs:choice>
			<xs:element name="priority" type="priorityFieldType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="validatesWith" type="validatesWithType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="onSave" type="hookType" />
				<xs:element name="onUpdate" type="hookType" />
				<xs:element name="onCreate" type="hookType" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="deletable" type="xs:boolean" />
	</xs:complexType>

	<xs:complexType name="validatesWithType">
		<xs:complexContent>
			<xs:extension base="hookType">
				<xs:attribute name="message" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="validatesType">
		<xs:attribute name="message" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="validatesLengthType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="min" type="xs:integer" />
				<xs:attribute name="is" type="xs:integer" />
				<xs:attribute name="max" type="xs:integer" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="validatesRangeType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="from" type="xs:string" />
				<xs:attribute name="to" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hookType">
		<xs:attribute name="bean" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[a-z][a-z0-9.]*.[a-zA-Z0-9]+" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="method" type="identifierType" use="required" />
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="validatesWith" type="validatesWithType" />
			<xs:element name="validatesPresence" type="validatesType" />
			<xs:element name="validatesPresenceOnCreate" type="validatesType" />
			<xs:element name="validatesUniqueness" type="validatesType" />
			<xs:element name="validatesLength" type="validatesLengthType" />
			<xs:element name="validatesPrecision" type="validatesLengthType" />
			<xs:element name="validatesScale" type="validatesLengthType" />
			<xs:element name="validatesRange" type="validatesRangeType" />
		</xs:choice>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="default" type="xs:string" />
		<xs:attribute name="readonly" type="xs:boolean" default="false" />
		<xs:attribute name="readonlyOnCreate" type="xs:boolean"
			default="false" />
	</xs:complexType>

	<xs:complexType name="belongsToFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="lookupField" type="identifierType"
					use="required" />
				<xs:attribute name="lazy" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hasManyFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="joinField" type="identifierType"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="dictionaryFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="dictionary" type="identifierType"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="enumFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="values" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-z][a-zA-Z0-9]*(,[a-z][a-zA-Z0-9]*)*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="priorityFieldType">
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="scope" type="identifierType" use="required" />
	</xs:complexType>

	<xs:simpleType name="identifierType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== 0000duck/mes/mes-plugins/mes-plugins-material-flow-resources/src/main/resources/materialFlowResources/model/position.xml
<?xml version="1.0" encoding="UTF-8"?>
<model name="position"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <belongsTo name="document" model="document" />
        <belongsTo name="product" model="product" plugin="basic"
                   required="true" />
        <decimal name="quantity" required="true" >
            <validatesRange from="0" exclusively="true"/>
        </decimal>
        <decimal name="price" default="0" />
        <string name="batch" />
        <string name="unit" persistent="false"/>
        <date name="productionDate" />
        <date name="expirationDate" />
        <priority name="number" scope="document"/>
    </fields>
    <hooks>
        <validatesWith class="com.qcadoo.mes.materialFlowResources.validators.PositionValidators" method="checkAttributesRequirement" />
        <validatesWith class="com.qcadoo.mes.materialFlowResources.validators.PositionValidators" method="validateDates" />
    </hooks>
</model>

=== 0000duck/mes/mes-plugins/mes-plugins-material-flow-documents/src/main/resources/materialFlowDocuments/model/position.xml
<?xml version="1.0" encoding="UTF-8"?>
<model name="position"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <priority name="number" scope="document"/>
        <belongsTo name="product" model="product" plugin="basic"
                   required="true" />
        <decimal name="quantity" required="true" />
        <decimal name="price" default="0" />
        <string name="batch" />
        <string name="unit" persistent="false"/>
        <date name="productionDate" />
        <date name="expirationDate" />
        <belongsTo name="document" model="document" />
    </fields>
    <hooks>
        <validatesWith class="com.qcadoo.mes.materialFlowDocuments.validators.PositionValidators" method="checkAttributesRequirement" />
    </hooks>
</model>

=== 0000duck/mes/mes-plugins/mes-plugins-material-flow-documents/src/main/resources/materialFlowDocuments/model/document.xml
<?xml version="1.0" encoding="UTF-8"?>
<model name="document" activable="true" auditable="true"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <string name="number" required="true" unique="true">
            <validatesLength max="255" />
        </string>
        <enum name="type" values="01receipt,02internalInbound,03internalOutbound,04release,05transfer" required="true" />
        <datetime name="time" required="true" />
        <enum name="state" values="01draft,02accepted" default="01draft" required="true" />
        <belongsTo name="locationFrom" model="location" plugin="materialFlow" />
        <belongsTo name="locationTo" model="location" plugin="materialFlow" />
        <belongsTo name="user" model="user" plugin="qcadooSecurity" required="true" />
        <belongsTo name="delivery" model="delivery" plugin="deliveries" />
        <hasMany name="positions" model="position" joinField="document" cascade="delete" copyable="true" />
    </fields>
    <hooks>
    </hooks>
</model>

=== 0000duck/mes/mes-plugins/mes-plugins-basic/src/main/resources/basic/model/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- *************************************************************************** 
	Copyright (c) 2010 Qcadoo Limited Project: Qcadoo MES Version: 1.1.7 This 
	file is part of Qcadoo. Qcadoo is free software; you can redistribute it 
	and/or modify it under the terms of the GNU Affero General Public License 
	as published by the Free Software Foundation; either version 3 of the License, 
	or (at your option) any later version. This program is distributed in the 
	hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
	warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
	GNU Affero General Public License for more details. You should have received 
	a copy of the GNU Affero General Public License along with this program; 
	if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth 
	Floor, Boston, MA 02110-1301 USA *************************************************************************** -->
<model name="product" activable="true" auditable="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<string name="number" required="true" unique="true">
			<validatesLength max="255" />
		</string>
		<string name="name" required="true">
			<validatesLength max="1024" />
		</string>
		<enum name="globalTypeOfMaterial" values="01component,02intermediate,03finalProduct,04waste" />
		<string name="ean" unique="true" />
		<dictionary name="category" dictionary="categories" />
		<dictionary name="unit" dictionary="units" required="true" />
		<hasMany name="substitutes" model="substitute" joinField="product"
			cascade="delete" copyable="true" />
		<hasMany name="substituteComponents" model="substituteComponent"
			joinField="product" cascade="nullify" />
		<string name="externalNumber" />
		<string name="description">
			<validatesLength max="2048" />
		</string>
<!-- 		<hasMany name="conversionItems" joinField="conversion" model="conversionItem" /> -->
		<hasMany name="productConversion" joinField="product" model="conversionItem" />
				
		<!-- PRODUCTS FAMILY TREE -->
		<enum values="01particularProduct,02productsFamily" name="productFamilyElementType" />
		<belongsTo name="productFamilyParent" model="product" />
		<hasMany name="productFamilyChildren" joinField="parent" model="product"/>
		<tree name="productFamilyChildrenTree" joinField="productFamilyParent" model="product"
			cascade="nullify" persistent="false" />
		<priority name="productFamilyPriority" scope="parent" />
		
	</fields>
	<hooks>
		<onCopy class="com.qcadoo.mes.basic.ProductService" method="clearExternalIdOnCopy" />
		<onCreate class="com.qcadoo.mes.basic.ProductService" method="fillUnit" />
	</hooks>
	<identifier expression="#number + ' - ' + #name" />
</model>

=== 0000duck/mes/mes-plugins/mes-plugins-production-scheduling/src/main/resources/productionScheduling/model/machineInOrderOperationComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 0.4.2

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="machineInOrderOperationComponent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<boolean name="useDefaultValue" />
		<priority name="priority" scope="orderOperationComponent" />
		<integer name="tpz" />
		<string name="parentTpz" persistent="false" />
		<integer name="tj" />
		<string name="parentTj" persistent="false" />
		<decimal name="parallel"  />
		<string name="parentParallel" persistent="false" />
		<boolean name="isActive" />
		<string name="parentIsActive" persistent="false" />
		<belongsTo name="machine" plugin="basic" model="machine" required="true" />
		<belongsTo name="orderOperationComponent" model="orderOperationComponent" required="true" />
	</fields>
	<hooks>
		<validatesWith class="com.qcadoo.mes.productionScheduling.NormOrderService"
			method="checkMachineInOrderOperationComponentUniqueness" />
		<validatesWith class="com.qcadoo.mes.productionScheduling.NormOrderService"
			method="checkMachineRequiredFields" />
	</hooks>
</model>
