=== 0000duck/mes/mes-core/src/main/resources/com/qcadoo/mes/core/view.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/view" xmlns="http://www.qcadoo.com/view">

	<xs:element name="views">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="view" type="viewType" />
			</xs:choice>
			<xs:attribute name="plugin" type="identifierType" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="viewType">
		<xs:sequence>
			<xs:element name="component" type="componentType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="onView" type="hookType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="model" type="identifierType" use="required" />
	</xs:complexType>
	
	<xs:complexType name="ribbonType">
		<xs:sequence>
			<xs:element name="group" type="ribbonGroupType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ribbonGroupType">
		<xs:all>
			<xs:element name="bigButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="bigButtons" type="ribbonComboType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButtons" type="ribbonComboType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:all>
		<xs:attribute name="name" type="identifierType" use="required" />
	</xs:complexType>

	<xs:complexType name="ribbonComboType">
		<xs:sequence>
			<xs:element name="bigButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="icon" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="ribbonActionType">
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="icon" type="xs:string" />
		<xs:attribute name="action" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="componentType">
		<xs:sequence>
			<xs:element name="ribbon" type="ribbonType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="option" type="optionsType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="identifierType" use="required" />
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="field" type="xs:string" />
		<xs:attribute name="source" type="xs:string" />
		<xs:attribute name="enabled" type="xs:boolean" />
		<xs:attribute name="visible" type="xs:boolean" />
	</xs:complexType>

	<xs:complexType name="optionsType">
		<xs:attribute name="type" type="identifierType" use="required" />
		<xs:attribute name="value" type="xs:string" />
		<!-- TODO - custom attributes -->
		<xs:attribute name="fields" type="xs:string" />
		<xs:attribute name="expression" type="xs:string" />
		<xs:attribute name="aggregation" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="width" type="xs:string" />
		<xs:anyAttribute/>
	</xs:complexType>

	<xs:complexType name="hookType">
		<xs:attribute name="bean" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[a-z][a-z0-9.]*.[a-zA-Z0-9]+" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="method" type="identifierType" use="required" />
	</xs:complexType>

	<xs:simpleType name="identifierType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== 0000duck/mes/mes-plugins/mes-plugins-stoppage/src/main/resources/stoppage/view/allStoppages.xml
<?xml version="1.0" encoding="UTF-8"?>

<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns="http://schema.qcadoo.org/view"
    	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
		name="allStoppages" modelName="stoppage" modelPlugin="stoppage">
	
		<component type="window" name="window">
			<ribbon>
				<group template="gridNewCopyAndRemoveAction" />
			</ribbon>
						
			<component type="grid" name="stoppage" reference="grid">
				<option type="column" name="order" fields="order" expression="#order['name']" link="true" width="40" />
				<option type="column" name="duration" fields="duration" link="true" width="20" />
				<option type="column" name="reason" fields="reason" link="true" />

				<option type="correspondingView" value="stoppage/allStoppagesForm" />
				<option type="correspondingComponent" value="form" />
				<option type="correspondingViewInModal" value="false" />
				
				<option type="searchable" value="reason, duration" />
				<option type="orderable" value="reason, duration" />
				<option type="fullscreen" value="true" />
				<option type="multiselect" value="true" />
				<option type="order" column="duration" direction="desc" />
			</component>
			<option type="fixedHeight" value="true" />
			<option type="header" value="false" />
		</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-operational-tasks/src/main/resources/operationalTasks/view/operationalTasksList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view name="operationalTasksList" modelName="operationalTaskDto"
	  defaultAuthorizationRole="ROLE_PLANNING" menuAccessible="true"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd">

	<component type="window" name="window">

		<ribbon>
			<template name="standardGridTemplate" />
		</ribbon>

		<component type="form" name="form" reference="form">
			<component type="gridLayout" name="mainTabGridLayout"
				columns="3" rows="2" hasBorder="false">
				<layoutElement column="1" row="1">
					<component type="lookup" name="productIn" field="productIn"
						reference="productIn">
						<option type="column" name="name" fields="name" link="true"
							width="200" />
						<option type="searchable" value="name,number" />
						<option type="orderable" value="name,number" />

						<option type="expression"
							value="#number + ' - ' + #name" />
						<option type="fieldCode" value="number" />
					</component>
				</layoutElement>
				<layoutElement column="2" row="1">
					<component type="lookup" name="productOut" field="productOut"
						reference="productOut">
						<option type="column" name="name" fields="name" link="true"
							width="200" />

						<option type="searchable" value="name,number" />
						<option type="orderable" value="name,number" />

						<option type="expression"
							value="#number + ' - ' + #name" />
						<option type="fieldCode" value="number" />
					</component>
				</layoutElement>
				<layoutElement column="1" row="2" width="3">
					<component type="grid" name="operationalTasksList"
						reference="grid">
						<option type="column" name="number" fields="number" link="true" width="75" />
						<option type="column" name="name" fields="name" link="true" width="125" />
						<option type="column" name="startDate" fields="startDate" width="100" />
						<option type="column" name="finishDate" fields="finishDate" width="100"/>
						<option type="column" name="staffName" fields="staffName" width="125" />
						<option type="column" name="productionLineName" fields="productionLineName" width="100"/>
						<option type="column" name="workstationName" fields="workstationName" width="100" />

						<option type="order" column="name" direction="asc" />

						<option type="searchable" value="name,number,startDate,finishDate,staffName,productionLineName,workstationName" />
						<option type="orderable" value="name,number,startDate,finishDate,staffName,productionLineName,workstationName" />

						<option type="correspondingView" value="operationalTasks/operationalTaskDetails" />
						<option type="correspondingComponent" value="form" />

						<option type="fullscreen" value="true" />
						<option type="multiselect" value="true" />

						<option type="fixedHeight" value="true" />
						<option type="header" value="false" />
					</component>
				</layoutElement>
			</component>

			<option type="header" value="true" />
		</component>

	</component>

</view>

=== 0000duck/mes/mes-plugins/mes-plugins-assignment-to-shift/src/main/resources/assignmentToShift/view/assignmentToShiftList.xml
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.3

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view defaultAuthorizationRole="ROLE_BASE_FUNCTIONALITY" name="assignmentToShiftList" modelName="assignmentToShift"
	  menuAccessible="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd">

	<component type="window" name="window" reference="window">

		<ribbon>
			<template name="standardGridTemplate"/>
			<group name="status">
				<bigButton name="state" icon="startIcon24.png" state="disabled">
					<script>
						<![CDATA[
							this.addOnChangeListener({
								onClick: function() {

								var actualState = this.actualState;

									if (actualState == "draft") {
										if (window.confirm("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.accepted.confirm)}")) {
											#{grid}.performEvent('changeState', ['02accepted']);
										};
									} else if (actualState == "accepted") {
										if (window.confirm("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.duringCorrection.confirm)}")) {
											#{grid}.performEvent('changeState', ['03duringCorrection']);
										};
									} else if (actualState == "duringCorrection") {
										if (window.confirm("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.corrected.confirm)}")) {
											#{grid}.performEvent('changeState', ['04corrected']);
										};
									} else if (actualState == "corrected") {
										if (window.confirm("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.duringCorrection.confirm)}")) {
											#{grid}.performEvent('changeState', ['03duringCorrection']);
										};
									}
								}
							});
						]]>
					</script>
				</bigButton>
			</group>
		</ribbon>

		<component type="grid" name="assignmentToShiftList"
				   reference="grid">
			<script>
				<![CDATA[
					var buttonsStatus = ["status.state"];

					var deleteButton = #{window}.getRibbonItem("actions.delete");

					var stateButton = #{window}.getRibbonItem("status.state");

					var listener = {
						onChange: function(selectedEntitiesArray) {
							if (!selectedEntitiesArray || selectedEntitiesArray.length == 0) {
								deleteButton.disable();
								stateButton.disable();
							} else {
								var differentStates = statesAreDifferent(selectedEntitiesArray);

								var state = selectedEntitiesArray[0].fields.state;

								var isDraft = (state == "01draft");
								var isAccepted = (state == "02accepted");
                                var isDuringCorrection = (state == "03duringCorrection");
 								var isCorrected = (state == "04corrected");

 								if (differentStates) {
 									deleteButton.disable("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.message.differentStates)}");
									stateButton.disable("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.message.differentStates)}");
								} else {
									if (isDraft) {
										deleteButton.enable();

										stateButton.enable();
										stateButton.actualState = "draft";
										stateButton.forState="02accepted";
										stateButton.setLabel("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.accepted)}");
										stateButton.confirmMessage = "#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.accepted.confirm)}";
									} else if (isAccepted) {
										deleteButton.disable("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.message.canNotDeleteAssignment)}");

										stateButton.enable();
										stateButton.actualState = "accepted";
										stateButton.forState="03duringCorrection";
										stateButton.setLabel("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.duringCorrection)}");
										stateButton.confirmMessage = "#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.duringCorrection.confirm)}";
									} else if (isDuringCorrection) {
										deleteButton.disable("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.message.canNotDeleteAssignment)}");

										stateButton.enable();
										stateButton.forState="04corrected";
										stateButton.actualState = "duringCorrection";
										stateButton.setLabel("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.corrected)}");
										stateButton.confirmMessage = "#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.corrected.confirm)}";
									} else if (isCorrected) {
										deleteButton.disable("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.message.canNotDeleteAssignment)}");

										stateButton.enable();
										stateButton.forState="03duringCorrection";
										stateButton.actualState = "corrected";
										stateButton.setLabel("#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.duringCorrection)}");
										stateButton.confirmMessage = "#{translate(assignmentToShift.assignmentToShiftList.window.ribbon.status.duringCorrection.confirm)}";
									}
								}
							}
						}
					}

					function statesAreDifferent(selectedEntitiesArray) {
						if (selectedEntitiesArray.length < 2) {
							return false;
						}

						for (var i = 1; i < selectedEntitiesArray.length; i++) {
							if (selectedEntitiesArray[i-1].fields.state != selectedEntitiesArray[i].fields.state) {
								return true;
							}
						}

						return false;
					}

					function enableButtons(buttonNames, message) {
						for (var buttonName in buttonNames) {
							if (message == '') {
								#{window}.getRibbonItem(buttonNames[buttonName]).enable();
							} else {
								#{window}.getRibbonItem(buttonNames[buttonName]).enable(message);
							}
						}
					}

					function disableButtons(buttonNames, message) {
						for (var buttonName in buttonNames) {
							if (message == '') {
								#{window}.getRibbonItem(buttonNames[buttonName]).disable();
							} else {
								#{window}.getRibbonItem(buttonNames[buttonName]).disable(message);
							}
						}
					}

					#{grid}.addOnChangeListener(listener);
				]]>
			</script>

			<option type="column" name="startDate" fields="startDate"
					link="true"/>
			<option type="column" name="shift" fields="shift" link="true"
					expression="#shift['name']"/>
			<option type="column" name="state" fields="state"/>

			<option type="order" column="startDate" direction="desc"/>

			<option type="correspondingView" value="assignmentToShift/assignmentToShiftDetails"/>
			<option type="correspondingComponent" value="form"/>

			<option type="searchable" value="startDate,shift,state"/>
			<option type="orderable" value="startDate"/>

			<option type="fullscreen" value="true"/>
			<option type="multiselect" value="true"/>

			<listener event="changeState"
					  class="com.qcadoo.mes.assignmentToShift.states.client.AssignmentToShiftStateChangeViewClient"
					  method="changeState"/>
		</component>

		<option type="fixedHeight" value="true"/>
		<option type="header" value="false"/>
	</component>

</view>

=== 0000duck/mes/mes-plugins/mes-plugins-technologies/src/main/resources/technologies/view/operationsList.xml
<?xml version="1.0" encoding="UTF-8"?>

<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="operationsList"
	modelName="operation"
	menuAccessible="true">
	
	<component type="window" name="window">
		<ribbon>
			<group template="gridNewCopyAndRemoveAction" />
		</ribbon>
		<component type="grid" name="operations" reference="grid">
			<option type="column" name="number" fields="number" link="true" />
			<option type="column" name="name" fields="name" link="true"
				width="200" />
			<option type="order" column="number" direction="desc" />
			<option type="correspondingView" value="technologies/operationDetails" />
			<option type="correspondingComponent" value="form" />
			<option type="searchable" value="number, name" />
			<option type="orderable" value="number, name" />
			<option type="fullscreen" value="true" />
			<option type="multiselect" value="true" />
		</component>
		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-material-flow/src/main/resources/materialFlow/view/transferTemplatesList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.1.6

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="transferTemplatesList" 
	modelName="transferTemplate"
	menuAccessible="true">
	
	<component type="window" name="window">
		<ribbon>
			<template name="standardGridTemplate" />
		</ribbon>
		
		<component type="grid" name="transferTemplateGrid" reference="grid">
			<option type="column" name="stockAreasFrom" fields="stockAreasFrom"
				expression="(#stockAreasFrom == null) ? '' : #stockAreasFrom['name']" link="true" />
			<option type="column" name="stockAreasTo" fields="stockAreasTo"
				expression="(#stockAreasTo == null) ? '' : #stockAreasTo['name']" link="true" />
			<option type="column" name="product" fields="product"
				expression="(#product == null) ? '' : #product['name']" link="true" />
				
			<option type="order" column="product" direction="asc" />
			
			<option type="searchable" value="stockAreasFrom,stockAreasTo,product" />
			<option type="orderable" value="stockAreasFrom,stockAreasTo,product" />
			
			<option type="correspondingView" value="materialFlow/transferTemplateDetails" />
			<option type="correspondingComponent" value="form" />
			
			<option type="fullscreen" value="true" />
			<option type="multiselect" value="true" />
		</component>
		
		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-genealogies/src/main/resources/genealogies/view/orderGenealogiesList.xml
<?xml version="1.0" encoding="UTF-8"?>

<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="orderGenealogiesList"
	modelPlugin="orders"
	modelName="order">
	
	<component type="window" name="window" reference="window">
		<ribbon>
			<group template="navigation" />
			<group template="gridNewCopyAndRemoveAction"/>
			<group name="autoGenealogy">
				<bigButton name="activeComplete" icon="genealogyClockIcon24.png"
					action="#{order}.fireEvent(autocompleteGenealogy,false);" state="enabled" />
				<bigButton name="lastUsedComplete" icon="genealogyArrowIcon24.png"
					action="#{order}.fireEvent(autocompleteGenealogy,true);" state="enabled" />
			</group>
		</ribbon>
		<component type="form" name="order" reference="order">
			<listener event="autocompleteGenealogy" class="com.qcadoo.mes.genealogies.AutoGenealogyService" method="autocompleteGenealogy" />
		</component>
		<component type="grid" name="genealogies" reference="grid" source="#{order}.genealogies">
			<option type="column" name="batch" fields="batch" link="true" />
			<option type="order" column="batch" direction="desc" />
			<option type="searchable" value="batch" />
			<option type="orderable" value="batch" />
			<option type="correspondingView" value="genealogies/orderGenealogyDetails" />
			<option type="correspondingComponent" value="form" />
			<option type="height" value="100" />
			<option type="fullscreen" value="true" />
		</component>
		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-production-per-shift/src/main/resources/productionPerShift/view/productionPerShift.xml
<view name="productionPerShift" modelName="order" modelPlugin="orders"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd">
	<component type="window" name="window" reference="window">
		<ribbon>
			<group name="navigation">
				<bigButton name="back" action="#{window}.performBack;"
					icon="backIcon24.png" />
			</group>
			<group name="action">
				<bigButton name="save" icon="saveIcon24.png" state="enabled"
					action="#{form}.performSave;" />
			</group>
		</ribbon>
		<component type="form" name="form" reference="form">
			<component type="borderLayout" name="plannedProgress">
				<component type="gridLayout" name="plannedProgressGridLayout"
					columns="1" rows="3">
					<layoutElement column="1" row="1">
						<component type="select" name="plannedProgressType"
							field="#{form}.plannedProgressType" reference="plannedProgressType">
						</component>
					</layoutElement>
					<layoutElement column="1" row="2">
						<component type="textarea" name="commentReasonTypeCorrectionDateFrom"
							field="#{form}.commentReasonTypeCorrectionDateFrom" reference="commentReasonTypeCorrectionDateFrom"
							defaultEnabled="false">
						</component>
					</layoutElement>
					<layoutElement column="1" row="2">
						<component type="calendar" name="orderStartDate"
							field="#{form}.correctedDateFrom" reference="orderStartDate"
							defaultEnabled="false">
							<option type="withTimePicker" value="true" />
						</component>
					</layoutElement>
					<layoutElement column="1" row="3">
						<component type="checkbox" name="wasItCorrected"
							reference="wasItCorrected" defaultEnabled="false">
						</component>
					</layoutElement>
				</component>
				<option type="label" value="plannedProgressLabel" />
			</component>
		</component>
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-material-flow/classes/materialFlow/view/transfers.xml
<?xml version="1.0" encoding="UTF-8"?>

<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="transfers" 
	modelName="transfer" 
	menuAccessible="true">
		<component type="window" name="window">
			<ribbon>
				<group template="gridNewCopyAndRemoveAction" />
			</ribbon>
			<component type="grid" name="grid" reference="grid">
				<option type="column" name="number" fields="number" link="true" width="150" />
				<option type="column" name="type" fields="type" />
				<option type="column" name="date" fields="date" />
				<option type="column" name="from" fields="from" 
				expression="#stockAreas['name']" />
				<option type="column" name="to" fields="to" 
				expression="#stockAreas['name']" />
				<option type="column" name="product" fields="product"
				expression="#product['name']" />
				<option type="column" name="quantity" fields="quantity" />
				<option type="column" name="staff" fields="staff"
				expression="#staff['name']" />
				<option type="order" column="number" direction="asc" />
				<option type="searchable" value="number" />
				<option type="orderable" value="number" />
				<option type="correspondingView" value="materialFlow/transferDetails" />
				<option type="correspondingComponent" value="form" />
				<option type="fullscreen" value="true" />
				<option type="multiselect" value="true" />
			</component>
			<option type="fixedHeight" value="true" />
			<option type="header" value="false" />
		</component>
</view>
