=== 0000duck/mes/mes-core/src/main/resources/com/qcadoo/mes/core/view.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/view" xmlns="http://www.qcadoo.com/view">

	<xs:element name="views">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="view" type="viewType" />
			</xs:choice>
			<xs:attribute name="plugin" type="identifierType" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="viewType">
		<xs:sequence>
			<xs:element name="component" type="componentType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="onView" type="hookType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="model" type="identifierType" use="required" />
	</xs:complexType>
	
	<xs:complexType name="ribbonType">
		<xs:sequence>
			<xs:element name="group" type="ribbonGroupType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ribbonGroupType">
		<xs:all>
			<xs:element name="bigButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="bigButtons" type="ribbonComboType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButtons" type="ribbonComboType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:all>
		<xs:attribute name="name" type="identifierType" use="required" />
	</xs:complexType>

	<xs:complexType name="ribbonComboType">
		<xs:sequence>
			<xs:element name="bigButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="icon" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="ribbonActionType">
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="icon" type="xs:string" />
		<xs:attribute name="action" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="componentType">
		<xs:sequence>
			<xs:element name="ribbon" type="ribbonType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="option" type="optionsType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="identifierType" use="required" />
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="field" type="xs:string" />
		<xs:attribute name="source" type="xs:string" />
		<xs:attribute name="enabled" type="xs:boolean" />
		<xs:attribute name="visible" type="xs:boolean" />
	</xs:complexType>

	<xs:complexType name="optionsType">
		<xs:attribute name="type" type="identifierType" use="required" />
		<xs:attribute name="value" type="xs:string" />
		<!-- TODO - custom attributes -->
		<xs:attribute name="fields" type="xs:string" />
		<xs:attribute name="expression" type="xs:string" />
		<xs:attribute name="aggregation" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="width" type="xs:string" />
		<xs:anyAttribute/>
	</xs:complexType>

	<xs:complexType name="hookType">
		<xs:attribute name="bean" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[a-z][a-z0-9.]*.[a-zA-Z0-9]+" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="method" type="identifierType" use="required" />
	</xs:complexType>

	<xs:simpleType name="identifierType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== 0000duck/mes/mes-plugins/mes-plugins-order-groups/src/main/resources/orderGroups/view/orderGroupOrdersTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 0.4.10

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="orderGroupOrdersTable"
	modelName="order"
	modelPlugin="orders" >
	
	<component type="window" name="window" reference="window">
		<ribbon>
			<group name="navigation">
			     <bigButton name="select" icon="acceptIcon24.png" state="disabled" >
			         <script>
			             <![CDATA[
			                 this.addOnChangeListener({
			                     onClick: function() {
			                     	#{form}.fireEvent(this, 'prepareConfirmText');
			                     }
			                 });

							#{confirmBoxTextHolder}.addOnChangeListener({
								onSetValue: function(value) {
									#{confirmBoxTextHolder}.performUpdateState();
									if (confirmReAssigment()) {
			                        	#{form}.fireEvent(this, 'addOrdersToGroup');
			                        }
								}
							});
			                 
			                 #{orders}.addOnChangeListener({
			                     onChange: function(selectedArray) {			                         
			                         if(!selectedArray || selectedArray.length == 0) {
			                             this.disable();
			                         } else {
			                             this.enable();
			                         }
			                     }
			                 });                           
			                 
			                 function confirmReAssigment() {
			                 	var message = #{confirmBoxTextHolder}.getValue().content.value;
			                 	if (!message) {
			                 		return false;
			                 	} else if (message != "NULL") {
                                	return confirm(message);
                                }
                                return true;
			                 }
			             ]]>
			         </script>
			     </bigButton>
			     <bigButton name="cancel" icon="cancelIcon24.png" action="#{window}.performBack;" />
			</group>
		</ribbon>
		
		<component type="form" name="orderGroup" reference="orderGroup" defaultVisible="false" >
		</component>
		
		<component type="form" name="orderGroupOrders" reference="form">
			<component type="gridLayout" name="gridLayout" columns="1" rows="2">
				<layoutElement column="1" row="1">
					<component type="grid" name="orders" reference="orders" >
					   <option type="column" name="number" fields="number" width="75" />
					   <option type="column" name="name" fields="name" width="200" />
					   <option type="column" name="orderGroup" fields="orderGroup" expression="#orderGroup != null ? #orderGroup['name'] : ''" width="200" />
					   <option type="column" name="orderGroupId" fields="orderGroup" hidden="true" />
                       <option type="column" name="dateFromShort" fields="dateFrom" width="160" />
                       <option type="column" name="dateToShort" fields="dateTo" width="160" />
                            
                       <option type="searchable" value="number,name,dateFrom,dateTo" />
                       <option type="orderable" value="number,name,dateFrom,dateTo" />
                        
                       <option type="order" column="number" direction="desc" />
                       <option type="multiselect" value="true" />
					</component>
					<component type="textarea" name="confirmBoxTextHolder" reference="confirmBoxTextHolder" defaultVisible="false" />
				</layoutElement>
			</component>
			<option type="header" value="true" />
			<option type="expression" value="#name" />
			<option type="expressionNew" value="#name" />
			
			<listener event="addOrdersToGroup" class="com.qcadoo.mes.orderGroups.OrderGroupsService" method="addOrdersToGroup" />
			<listener event="prepareConfirmText" class="com.qcadoo.mes.orderGroups.OrderGroupsService" method="prepareConfirmText" />
			
		</component>
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-material-flow/src/main/resources/materialFlow/view/resourcesList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.1.6

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="resourcesList" 
	modelName="resource" 
	menuAccessible="true">

	<component type="window" name="window">
		<ribbon>
			<template name="standardGridTemplate" />
		</ribbon>

		<component type="grid" name="resourceGrid" reference="grid">
			<option type="column" name="stockAreas" fields="stockAreas"
				expression="(#stockAreas == null) ? '' : #stockAreas['name']" link="true" />
			<option type="column" name="product" fields="product"
				expression="(#product == null) ? '' : #product['name']" link="true" />
			<option type="column" name="quantity" fields="quantity" />
			<option type="column" name="time" fields="time" />

			<option type="order" column="product" direction="asc" />

			<option type="searchable" value="stockAreas,product,quantity,time" />
			<option type="orderable" value="stockAreas,product,quantity,time" />

			<option type="correspondingView" value="materialFlow/resourceDetails" />
			<option type="correspondingComponent" value="form" />

			<option type="fullscreen" value="true" />
			<option type="multiselect" value="true" />
		</component>

		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-simple-material-balance/src/main/resources/simpleMaterialBalance/view/simpleMaterialBalanceStockAreasComponentDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="simpleMaterialBalanceStockAreasComponentDetails"
	modelName="simpleMaterialBalanceStockAreasComponent">
	
	<component type="window" name="window">
		<ribbon>
			<template name="standardFormTemplate" includeItems="navigation.back, actions.saveBack"/>
		</ribbon>
		<component type="form" name="simpleMaterialBalanceStockAreasComponent"
			reference="form">
			<component type="gridLayout" name="gridLayout" columns="1" rows="1">
				<layoutElement column="1" row="1">
					<component type="lookup" name="stockAreas" field="stockAreas">
						<option type="column" name="name" fields="name" link="true"
							width="200" />
						<option type="searchable" value="number" />
						<option type="orderable" value="number" />
						<option type="expression"
							value="'&lt;b&gt;' + #number + '&lt;/b&gt; - ' + #name" />
						<option type="fieldCode" value="number" />
					</component>
				</layoutElement>
			</component>
			<option type="header" value="true" />
			<option type="expression" value="#name" />
		</component>
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-orders/src/main/resources/orders/view/schedulesList.xml
<view defaultAuthorizationRole="ROLE_PLANNING" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://schema.qcadoo.org/view"
      xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
      name="schedulesList" modelName="schedule" menuAccessible="true">

    <component type="window" name="window" reference="window">
        <ribbon>
            <template name="standardGridTemplate"/>
        </ribbon>

        <component type="grid" name="schedules" reference="grid">
            <option type="column" name="number" fields="number" link="true" width="40"/>
            <option type="column" name="name" fields="name" link="true" width="50"/>
            <option type="column" name="state" fields="state" link="true" width="40"/>
            <option type="column" name="startTime" fields="startTime" width="50"/>
            <option type="column" name="sortOrder" fields="sortOrder" width="60"/>
            <option type="column" name="workstationAssignCriterion" fields="workstationAssignCriterion" width="60"/>
            <option type="column" name="workerAssignCriterion" fields="workerAssignCriterion" width="60"/>
            <option type="column" name="approveTime" fields="approveTime" width="50"/>

            <option type="correspondingView" value="orders/scheduleDetails"/>
            <option type="correspondingComponent" value="form"/>

            <option type="order" column="number" direction="desc"/>

            <option type="searchable"
                    value="name,number,state,startTime,sortOrder,workstationAssignCriterion,workerAssignCriterion,approveTime"/>
            <option type="orderable"
                    value="name,number,state,startTime,sortOrder,workstationAssignCriterion,workerAssignCriterion,approveTime"/>

            <option type="fullscreen" value="true"/>
            <option type="multiselect" value="true"/>
        </component>

        <option type="fixedHeight" value="true"/>
        <option type="header" value="false"/>
    </component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-basic/src/main/resources/basic/view/factoryDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view defaultAuthorizationRole="ROLE_COMPANY_STRUCTURE" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
      xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
      name="factoryDetails" modelName="factory">

    <component type="window" name="window">

        <ribbon>
            <template name="standardFormTemplate"/>
        </ribbon>
        <windowTab name="mainTab">

            <component type="form" name="form" reference="form">
                <component type="gridLayout" name="gridLayout" columns="3"
                           rows="6">
                    <layoutElement column="1" row="1">
                        <component type="input" name="number" field="number">
                            <option type="alignment" value="right"/>
                        </component>
                    </layoutElement>
                    <layoutElement column="1" row="2" height="2">
                        <component type="textarea" name="name" field="name"/>
                    </layoutElement>
                    <layoutElement column="1" row="4" height="1">
                        <component type="input" name="city" field="city"/>
                    </layoutElement>
                    <layoutElement column="2" row="1" height="6">
                        <component type="lookup" name="divisionsLookup" reference="divisionsLookup"
                                   field="#{form}.divisions" defaultVisible="false" persistent="false"
                                   hasLabel="false">
                            <option type="column" name="name" fields="name" link="true"/>

                            <option type="searchable" value="number,name"/>
                            <option type="orderable" value="number,name"/>

                            <option type="expression" value="#number + ' - ' + #name"/>
                            <option type="fieldCode" value="number"/>

                            <option type="multiselect" value="true"/>
                            <criteriaModifier
                                    class="com.qcadoo.mes.basic.criteriaModifiers.BasicDivisionCriteriaModifiers"
                                    method="showDivisionWithoutFactory"/>
                        </component>
                        <component type="grid" name="divisions" reference="divisions"
                                   source="#{form}.divisions">
                            <option type="column" name="number" fields="number"/>
                            <option type="column" name="name" fields="name"/>

                            <option type="order" column="number" direction="asc"/>

                            <option type="searchable" value="number,name"/>
                            <option type="orderable" value="number,name"/>

                            <option type="weakRelation" value="true"/>
                            <option type="correspondingLookup" value="divisionsLookup"/>

                            <option type="creatable" value="true"/>
                            <option type="deletable" value="true"/>
                            <option type="fullscreen" value="true"/>
                            <option type="multiselect" value="true"/>
                            <option type="paginable" value="true"/>
                        </component>
                    </layoutElement>
                </component>

                <option type="header" value="true"/>
                <option type="expression" value="#name"/>
            </component>
        </windowTab>
    </component>

</view>

=== 0000duck/mes/mes-plugins/mes-plugins-deliveries/src/main/resources/deliveries/view/deliveriesList.xml
<view name="deliveriesList" modelName="delivery" menuAccessible="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://schema.qcadoo.org/view" xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd">
	<component type="window" name="window">
		<ribbon>
			<template name="standardGridTemplate" />
		</ribbon>
		<component type="grid" name="deliveriesList" reference="grid">
			<option type="column" name="number" fields="number" link="true"	/>
			<option type="column" name="name" fields="name" link="true" />
			<option type="column" name="supplier" fields="supplier" expression="supplier['name']" />
			<option type="column" name="deliveryDate" fields="deliveryDate"  />
			<option type="column" name="deliveryDate" fields="deliveryDate"  />
			<option type="column" name="state" fields="state"  />
			<option type="column" name="createDate" fields="createDate"  />
			<option type="order" column="name" direction="asc" />
			<option type="correspondingView" value="deliveries/deliveryDetails" />
			<option type="correspondingComponent" value="form" />
			<option type="searchable" value="name,number" />
			<option type="orderable" value="name,number" />
			<option type="fullscreen" value="true" />
			<option type="multiselect" value="true" />
		</component>
		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
	</component>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-basic-production-counting/src/main/resources/basicProductionCounting/view/basicProductionCountingList.xml
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 0.4.10

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view"
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="basicProductionCountingList" modelName="order" modelPlugin="orders">

	<!-- name="basicProductionCountingList" modelName="basicProductionCounting" 
		menuAccessible="true"> -->

	<component type="window" name="window">
		<ribbon>
			<group template="navigation" />
		</ribbon>
		<component type="form" name="order" reference="order"/>
		<component type="form" name="basicProductionCounting" reference="form">
			<component type="grid" name="countingList" reference="grid"
				source="#{order}.basicProductionCountings">
				<option type="column" name="productNumber" fields="product"
					expression="#product['number']" link="true"/>
				<option type="column" name="productName" fields="product"
					expression="#product['name']" link="true"/>
				<option type="column" name="plannedQuantity" fields="plannedQuantity" />
				<option type="column" name="producedQuantity" fields="producedQuantity" />
				<option type="column" name="usedQuantity" fields="usedQuantity" />
				<option type="column" name="productType" expression="#product['typeOfMaterial']" hidden="true"/>
				<option type="order" column="productType" direction="desc" />
				<option type="correspondingView"
					value="basicProductionCounting/basicProductionCountingDetails" />
				<option type="correspondingComponent" value="form" />
				<option type="paginable" value="false" />
				<option type="fullscreen" value="true" />
				<option type="multiselect" value="true" />
			</component>
			</component>
		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
		
	</component>
	<hooks>
	<beforeRender
			class="com.qcadoo.mes.basicProductionCounting.BasicProductionCountingService"
			method="setUneditableGridWhenOrderTypeRecordingIsBasic" />
	</hooks>
</view>

=== 0000duck/mes/mes-plugins/inventory/src/main/resources/inventory/view/inventoriesList.xml
<?xml version="1.0" encoding="UTF-8"?>

<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="inventoriesList" 
	menuAccessible="true">
		<component type="window" name="window">
			<ribbon>
				<group template="gridNewCopyAndRemoveAction" />
			</ribbon>
			<component type="grid" name="grid" reference="grid">
				<option type="column" name="warehouse" fields="warehouse" />
				<option type="column" name="product" fields="product"
				expression="#product['name']" />
				<option type="column" name="quantity" fields="quantity" />
			</component>
			<option type="fixedHeight" value="true" />
			<option type="header" value="false" />
		</component>
</view>
