=== 0000duck/mes/mes-core/src/main/resources/com/qcadoo/mes/core/view.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/view" xmlns="http://www.qcadoo.com/view">

	<xs:element name="views">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="view" type="viewType" />
			</xs:choice>
			<xs:attribute name="plugin" type="identifierType" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="viewType">
		<xs:sequence>
			<xs:element name="component" type="componentType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="onView" type="hookType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="model" type="identifierType" use="required" />
	</xs:complexType>
	
	<xs:complexType name="ribbonType">
		<xs:sequence>
			<xs:element name="group" type="ribbonGroupType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ribbonGroupType">
		<xs:all>
			<xs:element name="bigButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="bigButtons" type="ribbonComboType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButtons" type="ribbonComboType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:all>
		<xs:attribute name="name" type="identifierType" use="required" />
	</xs:complexType>

	<xs:complexType name="ribbonComboType">
		<xs:sequence>
			<xs:element name="bigButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smallButton" type="ribbonActionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="icon" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="ribbonActionType">
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="icon" type="xs:string" />
		<xs:attribute name="action" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="componentType">
		<xs:sequence>
			<xs:element name="ribbon" type="ribbonType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="option" type="optionsType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="identifierType" use="required" />
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="field" type="xs:string" />
		<xs:attribute name="source" type="xs:string" />
		<xs:attribute name="enabled" type="xs:boolean" />
		<xs:attribute name="visible" type="xs:boolean" />
	</xs:complexType>

	<xs:complexType name="optionsType">
		<xs:attribute name="type" type="identifierType" use="required" />
		<xs:attribute name="value" type="xs:string" />
		<!-- TODO - custom attributes -->
		<xs:attribute name="fields" type="xs:string" />
		<xs:attribute name="expression" type="xs:string" />
		<xs:attribute name="aggregation" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="width" type="xs:string" />
		<xs:anyAttribute/>
	</xs:complexType>

	<xs:complexType name="hookType">
		<xs:attribute name="bean" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[a-z][a-z0-9.]*.[a-zA-Z0-9]+" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="method" type="identifierType" use="required" />
	</xs:complexType>

	<xs:simpleType name="identifierType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== 0000duck/mes/mes-plugins/mes-plugins-production-counting/src/main/resources/productionCounting/view/productionTrackingsForProductList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view defaultAuthorizationRole="ROLE_PRODUCTION_TRACKING" name="productionTrackingsForProductList"
	  modelName="productionTrackingForProductDto"
	  menuAccessible="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://schema.qcadoo.org/view"
	  xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd">

	<component type="window" name="window" reference="window">

		<ribbon>
			<template name="standardGridTemplate" includeItems="actions.refresh"/>
		</ribbon>

		<component type="grid" name="productionTrackingsForProductList"
				   reference="grid">
			<option type="column" name="productionTrackingNumber" fields="productionTrackingNumber" link="true"
					width="120"/>
			<option type="column" name="orderNumber" fields="orderNumber" link="true"
					width="200"/>
			<option type="column" name="technologyOperationComponentNumber"
					fields="technologyOperationComponentNumber" width="120"/>
			<option type="column" name="shiftName" fields="shiftName"
					width="80"/>
			<option type="column" name="staffName" fields="staffName"
					width="100"/>
			<option type="column" name="divisionNumber" fields="divisionNumber"
					width="80"/>
			<option type="column" name="productNumber" fields="productNumber"
					width="100"/>
			<option type="column" name="plannedQuantity" fields="plannedQuantity"
					width="80"/>
			<option type="column" name="usedQuantity" fields="usedQuantity"
					width="80"/>
			<option type="column" name="productUnit" fields="productUnit"
					width="60"/>
			<option type="column" name="productionTrackingState" fields="productionTrackingState"
					width="90"/>
			<option type="column" name="productionTrackingCreateDate" fields="productionTrackingCreateDate"
					width="100"/>
			<option type="column" name="productionTrackingLastTracking" fields="productionTrackingLastTracking"
					expression="#productionTrackingLastTracking" width="60"/>
			<option type="column" name="productionTrackingTimeRangeFrom" fields="productionTrackingTimeRangeFrom"
					width="100"/>
			<option type="column" name="productionTrackingTimeRangeTo" fields="productionTrackingTimeRangeTo"
					width="100"/>
			<option type="column" name="orderState" fields="orderState" hidden="true"/>

			<option type="order" column="productionTrackingNumber" direction="asc"/>

			<option type="searchable"
					value="productionTrackingNumber,orderNumber,technologyOperationComponentNumber,shiftName,staffName,divisionNumber,productNumber,plannedQuantity,usedQuantity,productUnit,productionTrackingState,productionTrackingCreateDate,productionTrackingLastTracking,productionTrackingTimeRangeFrom,productionTrackingTimeRangeTo"/>
			<option type="orderable"
					value="productionTrackingNumber,orderNumber,technologyOperationComponentNumber,shiftName,staffName,divisionNumber,productNumber,plannedQuantity,usedQuantity,productUnit,productionTrackingState,productionTrackingCreateDate,productionTrackingLastTracking,productionTrackingTimeRangeFrom,productionTrackingTimeRangeTo"/>

			<option type="correspondingView" value="productionCounting/productionTrackingDetails"/>
			<option type="correspondingComponent" value="form"/>

			<option type="fullscreen" value="true"/>
			<option type="multiselect" value="true"/>
		</component>

		<option type="fixedHeight" value="true"/>
		<option type="header" value="false"/>
	</component>

</view>

=== 0000duck/mes/mes-plugins/mes-plugins-basic/src/main/resources/basic/view/currencyDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 0.4.6

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="currencyDetails" 
	modelName="currency">
	
	<component type="window" name="window">
		<ribbon>
			
		</ribbon>
		<component type="form" name="currency" reference="form">
			<component type="gridLayout" name="gridLayout" columns="1"
				rows="1" hasBorders="false">
				<layoutElement column="1" row="1">
					<component type="lookup" name="currency">
						<option type="column" name="alphabeticCode" fields="alphabeticCode" />
						<option type="column" name="currency" fields="currency" />
						<option type="column" name="country" fields="country" />
						<option type="column" name="isoCode" fields="isoCode" />
						
						<option type="required" value="true" />
						<option type="searchable" value="currency,country,alphabeticCode,isoCode" />
						<option type="orderable" value="currency,country,alphabeticCode,isoCode" />
						<option type="expression" value="#alphabeticCode + ' - ' + #currency + ' (' + #country + ')'" />
						<option type="fieldCode" value="alphabeticCode" />
					</component>
				</layoutElement>
			</component>
			<option type="expression" value="#currency" />
			</component>
	</component>
	<hooks>
		<beforeRender class="com.qcadoo.mes.basic.ShiftsService" method="setHourFieldsState" />
	</hooks>
</view>

=== 0000duck/mes/mes-plugins/mes-plugins-production-scheduling/src/main/resources/productionScheduling/view/shiftsList.xml
<?xml version="1.0" encoding="UTF-8"?>

<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/view" 
	xsi:schemaLocation="http://schema.qcadoo.org/view http://schema.qcadoo.org/view.xsd"
	name="shiftsList" 
	modelName="shift" 
	menuAccessible="true">
	
	<component type="window" name="window">
		<ribbon>
			<template name="standardGridTemplate" />
			<group name="calendar">
				<bigButton name="showCalendar" action="" state="enabled" />
			</group>
		</ribbon>
		<component type="grid" name="shifts" reference="grid">
			<option type="column" name="name" fields="name" link="true" />
			<option type="order" column="name" direction="asc" />
			<option type="searchable" value="name" />
			<option type="orderable" value="name" />
			<option type="correspondingView" value="productionScheduling/shiftDetail" />
			<option type="correspondingComponent" value="form" />
			<option type="deletable" value="false" />
			<option type="creatable" value="false" />
			<option type="fullscreen" value="true" />
			<option type="multiselect" value="true" />
		</component>
		<option type="fixedHeight" value="true" />
		<option type="header" value="false" />
	</component>
</view>
